# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jemoji
  
# Site settings
title: "Fabio Nobre"
description: > # this means to ignore newlines until "email:"
  Random ideas, technology, computing, programming and related

email: eu@fabionobre.com.br
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Fabio Nobre'
author: 
  name: 'Fabio Nobre'
  bio: 'Web Developer, Java programmer in regular work, Rails developer in free time and trying to learn mobile.'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://fabionobre.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@eufabionobre'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/eufabionobre
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/fabionobre
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: linkedin
    url:  https://br.linkedin.com/in/eufabionobre
    desc: Connect with me on Linkedin
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
